### ISSUE TITLE
Is there any update for switch yang files

### ISSUE THREAD

**Issue by shangjiyu** [Huawei/yang#14]
I'm search for yang model files of CloudEngine S5731S-H24T4X-A, as it's [netconf support page](https://support.huawei.com/enterprise/en/doc/EDOC1100176998/c3add3cc) shows could be downloaded but no way.

**Comment by hwRouterYangAdmin** [comment]
Here are the messages I get from the website:
How Can I Download a YANG File?
The following provides an example of downloading a YANG file of the S5700 series switches.

1. Log in to http://support.huawei.com/enterprise.
2. Choose Software Download > Switches > Campus Switch > S5700.
3. Select software of the required version.
4. Click Download next to the YANG file of the required version.
