### ISSUE TITLE
Is there any update to huawei yang files?

### ISSUE THREAD

**Issue by MaoJianwei** [Huawei/yang#2]
For NE40E and CX600, is there any update to huawei yang files?

https://github.com/Huawei/yang/tree/master/network-router/8.9.10/huawei

As I see, latest product version is V800R012C00SPC300 now.

**Comment by lllyfeng** [comment]
pls see https://github.com/HuaweiDatacomm/yang

**Comment by MaoJianwei** [comment]
Thanks @lllyfeng

**Comment by MaoJianwei** [comment]
But it is the same as this repository? @lllyfeng

**Comment by MaoJianwei** [comment]
As I have seen, the handbook of Huawei router for development of YANG application is not publicly accessible.
So, are you sure it is ok to upload these yang files in this github repository?
I have some doubts if we can use these yang files openly and free of charge. @lllyfeng @guangyingzheng 
Thanks.

**Comment by lllyfeng** [comment]
@MaoJianwei Yang development handbook is planed, and will be obtained from huawei developer zone in future. We will try to open toolchains of northbound interface, if you have any requirement, please contact me.

**Comment by MaoJianwei** [comment]
Thanks, we can keep in touch here, so that can be referred by any users and contributors.
